Added SFTP file transfer resume support on both PUT and GET.
hierynomus/sshj pull request #775
Opened 2022-04-04 17:53 UTC by brenttyler

Internally SFTPFileTransfer has a few sanity checks to fall back to full replacement even if the resume flag is set.

SCP file transfers have not been changed to support this at this time.

2022-04-05 09:17 UTC, hierynomus commented
Please also write some tests

2022-04-05 21:53 UTC, brenttyler commented
> Please also write some tests

Done!

2022-04-07 11:12 UTC, hierynomus requested changes

2022-04-07 11:13 UTC, hierynomus commented
1 comment :)

2022-04-07 14:35 UTC, hierynomus commented
You need to add the .txt file to the ignore list of the license plugin in the build.

2022-04-07 15:44 UTC, brenttyler commented
> You need to add the .txt file to the ignore list of the license plugin in the build.

 I'm not as familiar with groovy scripting or license checks. I added the license header to the new JUnit test class which was missing and changed the license.excludes list to be the following. Will that work to exclude both of the test resources?

`excludes(['**/djb/Curve25519.java', '**/sshj/common/Base64.java', '**/com/hierynomus/sshj/userauth/keyprovider/bcrypt/*.java', '**/test/resources/files/test_file*.txt'])`

2022-04-07 16:16 UTC, brenttyler commented
Apparently that last commit created a security/snyk issue but I can't see the details.

2022-04-08 07:18 UTC, hierynomus commented on src/main/java/net/schmizz/sshj/sftp/SFTPFileTransfer.java
> -                if (resume && adjusted.getLength() != 0 && adjusted.getLength() < remote.getAttributes().getSize()) {
Is there an additional test for this?

2022-04-18 13:57 UTC, brenttyler commented on src/main/java/net/schmizz/sshj/xfer/FileTransfer.java
> +     * @param resume
Just following the precedent that was there with the existing javadoc

2022-04-18 14:03 UTC, brenttyler commented
Just curious what the thoughts on this PR are now and what else I can do to help move it forward?

2022-04-19 13:03 UTC, hierynomus commented
> Just curious what the thoughts on this PR are now and what else I can do to help move it forward?

I've been thinking about the API that you've added. I'm not entirely sure I'm comfortable with a plain boolean and the "magic" underneath. I'm thinking more along the lines of having the read/write interfaces expose an offset at where to start writing/reading. That would make the API a bit more versatile and less magic.

2022-04-19 14:29 UTC, hierynomus commented
> > > Just curious what the thoughts on this PR are now and what else I can do to help move it forward?
> > 
> > 
> > I've been thinking about the API that you've added. I'm not entirely sure I'm comfortable with a plain boolean and the "magic" underneath. I'm thinking more along the lines of having the read/write interfaces expose an offset at where to start writing/reading. That would make the API a bit more versatile and less magic.
> 
> Yeah, I can do that. Probably in my excitement to get it working I put too much of my use case into that but we should leave it up to the users of this API to know what they're asking for. They already have the tooling to discover what's on the destination already - the existence, current length, and last modified timestamp - with which to make informed offset decisions.
> 
> I'll work on that but it may be a few days.

I fully understand, and I do get the usecase, but as you also pointed out, all the bits to make it work are there, except for the "starting at a particular offset". Making the API more reusable will actually allow more usecases to be implemented.

2022-05-25 18:00 UTC, brenttyler commented
Anything else I can do to help finalize this PR? We've been running it in production for a while now with no issues.

2022-05-25 20:50 UTC, hierynomus approved these changes

2022-05-27 11:05 UTC, merged

2022-05-27 11:06 UTC, hierynomus commented
Thanks for the nudge, I've approved and merged it! 👍

2022-05-27 12:00 UTC, brenttyler commented
Thanks!